### ISSUE TITLE
Plzz Check

### ISSUE THREAD

**Issue by Sachin6189** [Sachin6189/Issue-Tracking-System#1]
Check kar ke bata aur kaise enhance kar skte h.

**Comment by FreakWolf** [comment]
everything looks good but try to make as many components a possible and try to make code short so that its easy to understand.
for example you can create :
1. Login.js 
2. logo.js or something like that
3. LoginForm.js
Where the main login content will be in LoginForm.js kyu ki in future you'll have to enter the users from the backend and confirm whether or not the user exits in the database so try to see little bit into future.
